title: peppynet
email: peppy@peppy.hr
description: >- # this means to ignore newlines until "baseurl:"
  peppynet is an independent Croatian software development company
  specializing in .NET/C# applications.
baseurl: ""
url: https://peppy.hr
github_username: fkelava

# Build settings
theme: minima
plugins:
  - jekyll-feed