title: peppynet
author: Fran Kelava
email: peppy@peppy.hr
description: >- # this means to ignore newlines until "baseurl:"
  peppynet is a one-man software development company
  specializing in .NET applications.
baseurl: ""
url: https://peppy.hr
github_username: fkelava

# Build settings
theme: minima
plugins:
  - jekyll-feed